### ISSUE TITLE
[FEAT] Convert to .exe

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/Choose-Your-Own-Adventure-Game#15]
I require the Python file to also be made into a .exe, and for the .exe file to automatically be updated if the Python is updated. 

There are python packages to do so.

If you are finding it hard, even if a gh-action is in place, to allow users to download a .exe from the releases on this repo, that would work too but not preferable.

**Comment by Nymphalys** [comment]
Hi I think i can work on this issue,Can you assign me?

**Comment by KendallDoesCoding** [comment]
> Hi I think i can work on this issue,Can you assign me?

Sure.

**Comment by KendallDoesCoding** [comment]
I found a GitHub action that can do this. https://github.com/marketplace/actions/build-exe-from-python-script

**Comment by KendallDoesCoding** [comment]
> I found a GitHub action that can do this. https://github.com/marketplace/actions/build-exe-from-python-script

I tried doing this in #16 but it didn't work. I need some help with this action. @Nymphalys would you be interested?

**Comment by Karthick47v2** [comment]
@KendallDoesCoding may I know the reason for why gh-action is not preferable?. Because isn't it easy for you and users as it will automatically build .exe for each new changes you commit.

**Comment by KendallDoesCoding** [comment]
I actually created this issue a long time ago and forgot the reason. Yess,
that's true can u link a Github action?
