### ISSUE TITLE
[FEATURE REQUEST] - Add a GUI

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/Choose-Your-Own-Adventure-Game#21]
Add a GUI to this Python project to make it look amazing!!

**Comment by Omppu42** [comment]
I can work on this one as well.

**Comment by KendallDoesCoding** [comment]
> I can work on this one as well.

Sure, go ahead!

**Comment by Omppu42** [comment]
I'll make a window where the question is in the center and 2 buttons bellow it. A cool image in the background. 
Any thoughts?

**Comment by KendallDoesCoding** [comment]
> I'll make a window where the question is in the center and 2 buttons bellow it. A cool image in the background. Any thoughts?

That's going to be amazing!

**Comment by KendallDoesCoding** [comment]
Can you make also a beginning frame (I can provide a picture for that, it should just say "Choose Your Own Adventure Game") and then in 2 seconds start the main thing.

**Comment by Omppu42** [comment]
Yeah I can, if you have a picture just send me it somehow!

**Comment by KendallDoesCoding** [comment]
You can use the image that will be made in #37 . If nobody wants to be assigned, I will do it!

**Comment by Omppu42** [comment]
Sure thing!

**Comment by KendallDoesCoding** [comment]
@Omppu42 this is the logo, thanks!
![image](https://user-images.githubusercontent.com/84712013/224911401-a9c7fd9f-df85-448a-b9f9-147676a842ce.png)

**Comment by Omppu42** [comment]
Great! I'll add it

**Comment by KendallDoesCoding** [comment]
Thanks, you will make the GUI using pygame?

**Comment by Omppu42** [comment]
Yes it's made using pygame, you can see the progress by checking the repository on my profile!

**Comment by Omppu42** [comment]
Ok, I'll take a look at that.

**Comment by KendallDoesCoding** [comment]
@Omppu42 Is it also possible to add a token system? When you win you get coins and with coins you can buy powerups, eg: continue even if died.

Please let me know.

**Comment by KendallDoesCoding** [comment]
> That's a project for another time. I'll have to finish the GUI first

Ok cool!
