### ISSUE TITLE
[FEAT] Make music volume less (playsound module)

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/Choose-Your-Own-Adventure-Game#26]
The music is slightly loud, make it just a bit softer user the playsound module.

**Comment by SahilSinghTomar** [comment]
I decreased the volume of the source.
Does this work??

**Comment by SahilSinghTomar** [comment]
you can use pygame module for this.

```python
import pygame

pygame.init()
pygame.mixer.init()
sound = pygame.mixer.Sound("music/sotb.mp3")
sound.set_volume(0.2)              # Now plays at 20% of full volume.
def music():
    sound.play()
```

**Comment by KendallDoesCoding** [comment]
> you can use pygame module for this.
> 
> ```python
> import pygame
> 
> pygame.init()
> pygame.mixer.init()
> sound = pygame.mixer.Sound("music/sotb.mp3")
> sound.set_volume(0.2)              # Now plays at 20% of full volume.
> def music():
>     sound.play()
> ```

Can you make a PR?

**Comment by SahilSinghTomar** [comment]
ok
