### ISSUE TITLE
[DOCS] Contributing Guidelines

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/Choose-Your-Own-Adventure-Game#3]
I require someone to create CONTRIBUTING GUIDELINES and link the file to the README.md

**Comment by deeproop** [comment]
Hello, I would like to work on this issue.

**Comment by KendallDoesCoding** [comment]
> Hello, I would like to work on this issue.

Sure!

**Comment by deeproop** [comment]
Hope it helps, if any changes are needed, will refactor the code again :)
