### ISSUE TITLE
Share copyright free music for the program (looking for 3 recommendations)

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/Choose-Your-Own-Adventure-Game#31]
Please share a YouTube link of copyright free music for the program.

**Comment by Fear-over** [comment]
In which file 
File path ?

**Comment by Fear-over** [comment]
I need add music in music file that it ?

**Comment by KendallDoesCoding** [comment]
@Fear-over Link youtube videos of copyright free music here and I will add them soon if I like it.

**Comment by KendallDoesCoding** [comment]
There are 7 songs added as of now, looking for about 10 so need 3 recommendations.

**Comment by AaryanTrivedi** [comment]
https://www.youtube.com/watch?v=rXoTj6mHHaQ

Share what specific kind of music do you need

**Comment by KendallDoesCoding** [comment]
> https://www.youtube.com/watch?v=rXoTj6mHHaQ
> 
> Share what specific kind of music do you need

any copyright FREE music works

**Comment by KendallDoesCoding** [comment]
preferably youtube links


*Thanks,*
*Kendall Does Coding*

*Portfolio
<https://cdc-aims.com/click?redirect=https%3A%2F%2Fkendalldoescoding.gq&dID=1678891208962&hashId=060de6478a47358f5315814fdd49f493dff92988d90dca1ba25e30911a8a60f18777e7&linkName=Portfolio>*
*Github
<https://cdc-aims.com/click?redirect=https%3A%2F%2Fgithub.com%2FKendallDoesCoding&dID=1678891208962&hashId=060de6478a47358f5315814fdd49f493dff92988d90dca1ba25e30911a8a60f18777e7&linkName=Github>*
*Youtube*
<https://cdc-aims.com/click?redirect=https%3A%2F%2Fkendalldoescoding.gq%2FcodingYT&dID=1678891208962&hashId=060de6478a47358f5315814fdd49f493dff92988d90dca1ba25e30911a8a60f18777e7&linkName=Youtube>
