### ISSUE TITLE
Loop song/Change song if music stopped (pygame module)

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/Choose-Your-Own-Adventure-Game#33]
In the beginning of the program, it asks the user if they want to play music. If they say yes the music plays. There are 7 songs defined to play as of now (and any song can play at random) but some songs can range from 1 minute and some up to 3 minutes. The songs (especially the short ones), may get over while the user is still playing the game. So, we need to make it so that if in the beginning the user wants to play music and later while the program is running if the song stops. Automatically pick a new song or loop the song that was playing before.

Please check out music.py for more info.

**Comment by KendallDoesCoding** [comment]
> I can look into this.

Sure. Should I assign you?

**Comment by Omppu42** [comment]
Sure

**Comment by KendallDoesCoding** [comment]
> Sure

Done!
