### ISSUE TITLE
[DOCS] Security Policy

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/Choose-Your-Own-Adventure-Game#4]
Create a Security Policy

[Example From Other Repo](https://github.com/KendallDoesCoding/portfolio/blob/main/.github/SECURITY.md)

**Comment by athulmekkoth** [comment]
can I work on this?

**Comment by KendallDoesCoding** [comment]
> can I work on this?

Sure!

**Comment by athulmekkoth** [comment]
is there anything extra to be included from the given example?

**Comment by KendallDoesCoding** [comment]
> is there anything extra to be included from the given example?

Nope

**Comment by KendallDoesCoding** [comment]
Any update on this @athulmekkoth?

**Comment by athulmekkoth** [comment]
Sorry I was little busy due to some personal emergency . I will finish it by today or tomorrow

**Comment by KendallDoesCoding** [comment]
> Sorry I was little busy due to some personal emergency . I will finish it by today or tomorrow

Hi Athul, no need to be sorry, I hope the emergency has been resolved, if it hasn't please take your time, no rush. I understand your busy..
