### ISSUE TITLE
GitPod does not start the game

### ISSUE THREAD

**Issue by AaryanTrivedi** [KendallDoesCoding/Choose-Your-Own-Adventure-Game#41]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to play the game on Gitpod and it did not start

![image](https://user-images.githubusercontent.com/34876037/224771720-b4163dba-e83e-4838-bdf4-96696b058bee.png)

**Comment by AaryanTrivedi** [comment]
![image](https://user-images.githubusercontent.com/34876037/224773304-29a439df-8ce8-490b-b440-c2f395e79b4a.png)

Also How do I make it run

**Comment by KendallDoesCoding** [comment]
Hi.

Will figure out what the issue is. Can you try running it locally. Run
main.py

**Comment by KendallDoesCoding** [comment]
@AaryanTrivedi - thanks for bringing this to my notice.

Well there are quite a few issues such as:
- automatically installed modules on Pip for windows are not automatically installed on Gitpod (such as numpy, matplotlib, etc)
- The snippet in the code, where it tells the users what plugins to download also doesn't work.
- The music doesn't work

I tried to fix all these issues, I just need to test that it works on Windows now and then will commit.

**Comment by KendallDoesCoding** [comment]
Fixed
