### ISSUE TITLE
Add color to GUI (pygame)

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/Choose-Your-Own-Adventure-Game#50]
Using pygame, add colours to the GUI!

https://stackoverflow.com/questions/66264628/add-text-into-a-colored-input-text-box-pygame

**Comment by Srinja333** [comment]
i know only python basics, am i applicable to do that?

**Comment by Srinja333** [comment]
ok

**Comment by Saksham093** [comment]
I would like to work on this issue... Would you assign me .

**Comment by KendallDoesCoding** [comment]
> Contributor

Sure.

**Comment by Saksham093** [comment]
Thank You .... assigning me this issue.

Now, I want to know what color to add for which segment like 

![](https://user-images.githubusercontent.com/69385787/225731261-535583c9-0685-415b-b680-295d819c0b3d.png)

The Input text color is fine, the 'Hi! What is you name?" 's color is not so good for reading

**Comment by KendallDoesCoding** [comment]
If you see chapters.py for every print or answer = input it jas
Fore.(COLOR) use that color, but if it looks bad then use any color of your
choice. If the system is setup, I can always change the colors.

**Comment by ishaan9006** [comment]
@KendallDoesCoding  Hey! I have changed the color of the text from black to white. Improves the visibility of the text. If it looks good, can I make a pull request?
![before](https://user-images.githubusercontent.com/72651834/227739890-763baed9-32ce-4308-8d9c-8c091b08f8cd.png)

![change](https://user-images.githubusercontent.com/72651834/227739901-404d9f5b-1d4c-4710-b976-3f4617307ccb.png)

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding Hey! I have changed the color of the text from black to white. Improves the visibility of the text. If it looks good, can I make a pull request?
> 
> ![change](https://user-images.githubusercontent.com/72651834/227739901-404d9f5b-1d4c-4710-b976-3f4617307ccb.png) ![before](https://user-images.githubusercontent.com/72651834/227739890-763baed9-32ce-4308-8d9c-8c091b08f8cd.png)

Can you do this throughtout the project too?

Yes, please make a PR.

**Comment by ishaan9006** [comment]
> > @KendallDoesCoding Hey! I have changed the color of the text from black to white. Improves the visibility of the text. If it looks good, can I make a pull request?
> > ![change](https://user-images.githubusercontent.com/72651834/227739901-404d9f5b-1d4c-4710-b976-3f4617307ccb.png) ![before](https://user-images.githubusercontent.com/72651834/227739890-763baed9-32ce-4308-8d9c-8c091b08f8cd.png)
> 
> Can you do this throughtout the project too?
> 
> Yes, please make a PR.

Sure

**Comment by ishaan9006** [comment]
@KendallDoesCoding I have made the PR, can you review it and let me know if you need any changes?
