### ISSUE TITLE
Change exit() to sys.exit(1)

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/Choose-Your-Own-Adventure-Game#55]
## Description
The `exit` or `quit` functions don&#x27;t exist at top-level if python is started with the `-S` flag, and will raise an error. Use `sys.exit()` instead.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/KendallDoesCoding/Choose-Your-Own-Adventure-Game/issue/PYL-R1722/occurrences/](https://deepsource.io/gh/KendallDoesCoding/Choose-Your-Own-Adventure-Game/issue/PYL-R1722/occurrences/)

![image](https://user-images.githubusercontent.com/84712013/226101502-22d8abcf-57c2-495d-9b22-6fe8074067aa.png)

**Comment by valanm22** [comment]
May I work on this?

**Comment by KendallDoesCoding** [comment]
> May I work on this?

Sure.
